"""
LGBT-related search terms for Peru Congress law searches.

These terms are used across all scrapers to ensure comprehensive
coverage of LGBT rights legislation in Peru.
"""

LGBT_SEARCH_TERMS = [
    "gay",
    "identidad de género",
    "mismo sexo",
    "no binarie",
    "no binario",
    "no binaria",
    "no-binario",
    "no-binaria",
    "bisex",
    "bisexual",
    "bisexualidad",
    "pareja del mismo sexo",
    "parejas del mismo sexo",
    "matrimonio igualitario",
    "matrimonio entre personas del mismo sexo",
    "gays",
    "comunidad gay",
    "LGBT",
    "LGTB",
    "LGBTI",
    "LGTBI",
    "LGBTIQ",
    "LGBTIQ+",
    "heteronorma",
    "heteronormativo",
    "heteronormatividad",
    "homoafectivo",
    "vínculos homoafectivos",
    "homofobia",
    "homofóbico",
    "homofóbica",
    "homosexual",
    "homosexualidad",
    "reconocimiento de identidad de género",
    "ley de identidad de género",
    "intersex",
    "intersexual",
    "intersexualidad",
    "lesbiana",
    "lesbianas",
    "lesbianidad",
    "lésbico",
    "del mismo sexo",
    "nombre social",
    "uso de nombre social",
    "orientación sexual",
    "diversidad sexual",
    "no discriminación por orientación sexual",
    "psicosexual",
    "psicosexualidad",
    "queer",
    "transexual",
    "transexualidad",
    "transfobia",
    "transfóbico",
    "transfóbica",
    "transgénero",
    "transgenero",
    # "trans",  # Too broad, commented out
    "reasignación de sexo",
    "adecuación de sexo",
    "cirugía de reasignación de sexo",
    "travesti",
    "travestis",
    "unión homoafectiva",
    "unión entre personas del mismo sexo",
    "unión civil",
    "unión civil no matrimonial",
    "crímenes de odio",
    "delitos de odio",
    # "igualdad",  # Too broad, commented out
    "no discriminación",
    "cambio de nombre",
    "rectificación de nombre",
    "rectificación de sexo",
]
